https://leetcode.com/problems/next-permutation/

A permutation of an array of integers is an arrangement of its members into a sequence or linear order.

For example, for arr = [1,2,3], the following are considered permutations of arr: [1,2,3], [1,3,2], [3,1,2], [2,3,1].
The next permutation of an array of integers is the next lexicographically greater permutation of its integer. More formally, if all the permutations of the array are sorted in one container according to their lexicographical order, then the next permutation of that array is the permutation that follows it in the sorted container. If such arrangement is not possible, the array must be rearranged as the lowest possible order (i.e., sorted in ascending order).

For example, the next permutation of arr = [1,2,3] is [1,3,2].
Similarly, the next permutation of arr = [2,3,1] is [3,1,2].
While the next permutation of arr = [3,2,1] is [1,2,3] because [3,2,1] does not have a lexicographical larger rearrangement.
Given an array of integers nums, find the next permutation of nums.

The replacement must be in place and use only constant extra memory.

In [ ]:
from typing import List
import numpy as np
from collections import OrderedDict
class Solution:
    def nextPermutation(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        
        n = len(nums)
        found = False
        for i in range(0, n-1): ## iterating through in reverse

            if nums[n-i-2] < nums[n-i-1]:  ## take closest value greater than x in n-i-1:, swap with n-i-2 and then sort n-i
                ##int("yes",n-i-2, nums[n-i-2], n-i-1, nums[n-i-1])
                
                br = False
                for idx in range(n-i-1,n):
                    print("idx",idx)
                    ## numbers expected to be sorted in descending order. so at any time value at idx <= value at n-i-2, break
                    index, val = idx, nums[idx]
                    if  (val <= nums[n-i-2]) :
                        print("break here")
                        br = True
                        break
                if br==True:
                    index = idx - 1
                else:
                    index = idx
                val = nums[index]

                temp = nums[n-i-2]
                #       print("temp", temp)
               #        print("nums0", nums)
               #        print(number_dict)
                nums[n-i-2] = val
                        
              #         print("nums1",nums)
                nums[index] = temp
                        
                        
                found = True
                ## we now sort everything from n-i-1 onwards in ascending order
         ##     print("nums", nums)
                #       print(" nums[:(n-i-1)]",  nums[:(n-i-1)])
                
                  ##    nums = nums[:(n-i-1)] + sorted(nums[(n-i-1):]) - sorted like this not allowed as want in place
                m = n-1
                for b in range(n-i-1,n):
                    if m<b:
                        break
                    temp = nums[b]
                    nums[b]=nums[m]
                    nums[m] = temp
                    m = m-1
                break
            if found==True:
                break
        if found == False: ## list in descending order
            for i in range(0,n):
                j = n-i-1
                ## print(i, j)
                if j < i:
                    break
                temp = nums[j]
                nums[j] = nums[i]
                nums[i] = temp
        return nums
        
        
                        

                
            
            

In [196]:
a = Solution()

In [174]:
nums = [16,27,25,23,25,16,12,9,1,2,7,20,19,23,16,0,6,22,16,11,8,27,9,2,20,2,13,7,25,29,12,12,18,29,27,13,16,1,22,9,3,21,29,14,7,8,14,5,0,23,16,1,20]

In [197]:
a.nextPermutation(nums = [2,1,3])

idx 2


[2, 3, 1]

In [193]:
1,3,2 -> 2,1,3

SyntaxError: invalid syntax (<ipython-input-193-9be28f1fc2b3>, line 1)

In [ ]:
2,3,1 -> 3,1,2

In [ ]:
[1,2,3,9,8,7]

In [48]:
a = [2,3,1] -> [3,1,2]

In [49]:
a[2:]

[3]

In [50]:
a = [1,2,3,4]

In [51]:
a[1:]

[2, 3, 4]

In [52]:
a[:-1]

[1, 2, 3]

In [ ]:
[2,3,1]  -> [3,1,2]

In [ ]:
[2,1,3] -> [2,3,1] -> [3,2,1]

In [ ]:
[4,1,3,3,2]

In [ ]:
[4,1,2,3]

In [ ]:
[4,2,3,1]

In [ ]:
[1,2,3]

In [ ]:
[2,3,1] -> [3,1,2]

In [ ]:
[3,4,2,1]

In [85]:
nums = [4,5,1,3,2]
n = len(nums)

In [88]:
i = 1

In [89]:
nums[n-i-2] < nums[n-i-1]

True

In [90]:
np.array(nums[n-i-1:])-nums[n-i-2]

array([2, 1])

In [100]:
diff = np.array(nums[n-i-1:])-nums[n-i-2]
diff[diff<0] = None


TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [98]:
diff = np.array()

array([2, 1])

In [93]:
diff[diff>0]

array([2, 1])

In [97]:
u11 = np.array([2,1,0])

In [96]:
u11 & (u11>0)

array([0, 1, 0], dtype=int32)

In [101]:
a = [3,2,1]

In [102]:
a.sort()

In [103]:
a

[1, 2, 3]